spring:
  application:
    name: 2025_SEASONTHON_TEAM_21_BE

  server:
    port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/SSLIM?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Hibernate가 @Table(name = "...")를 그대로 사용
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql # 앱 실행 시, 초기 삽입 데이터

apis:
  rtms:
    service-key: "2d4ea1d47d8bb9f264dac2c60c50527ce80b29540db5eaaa1e026f22f629e9de"
