spring:
  application:
    name: 2025_SEASONTHON_TEAM_21_BE

  server:
    port: 8080

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/seasonthon_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:dbpw}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Hibernate가 @Table(name = "...")를 그대로 사용
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql # 앱 실행 시, 초기 삽입 데이터