name: Deploy sslim-backend

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ✅ 부트 JAR만 빌드 (plain JAR 생성 안 함)
      - name: Build Spring Boot bootJar
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test
          ls -la build/libs

      # ✅ 산출물 존재 확인
      - name: Assert bootJar exists
        run: |
          set -e
          [ -f build/libs/app.jar ] || { echo "app.jar not found"; ls -la build/libs; exit 1; }

      # 필요 파일 전송
      - name: Copy compose/Dockerfile/app.jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          source:   "Dockerfile,docker-compose.yml,build/libs/app.jar"
          target:   "/home/${{ secrets.EC2_USER }}/SSLIM"
          strip_components: 0

      # 배포
      - name: Deploy via docker compose (no env file)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:         ${{ secrets.EC2_HOST }}
          username:     ${{ secrets.EC2_USER }}
          key:          ${{ secrets.EC2_SSH_KEY }}
          script_stop:  true
          script: |
            set -e
            COMPOSE_DIR="$HOME/SSLIM"
            cd "$COMPOSE_DIR"

            docker compose down --remove-orphans || true
            docker compose up -d --build

            # healthcheck 대기 (컨테이너명: sslim-app)
            for i in {1..30}; do
              sleep 2
              state=$(docker inspect --format='{{.State.Health.Status}}' sslim-app 2>/dev/null || true)
              [ "$state" = "healthy" ] && { echo "App healthy"; exit 0; }
            done
            echo "Healthcheck timeout. Recent logs:"
            docker compose logs --no-color --tail=200
            exit 1